modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
#logoFile="tfmg_stellaris_compat.png" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tfmg"
type = "required"
versionRange = "[1.0.2,1.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "stellaris"
type = "required"
versionRange = "[1.4.6,1.5.0)"
ordering = "AFTER"
side = "BOTH"